[project]
name = "flowpilot"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "celery[redis]>=5.6.3",
    "fastapi[standard]>=0.141.1",
    "langchain>=1.4.0",
    "langgraph>=1.2.11",
    "psycopg[binary]>=3.3.5",
    "pydantic>=2,<3",
    "redis>=6.4.0",
    "sqlalchemy[asyncio]>=2,<3",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
