import os
import unittest
import warnings
from datetime import UTC, date, datetime, timedelta
from decimal import Decimal
from uuid import uuid4

from sqlalchemy import create_engine, create_mock_engine, inspect, select, text
from sqlalchemy.exc import DBAPIError, IntegrityError, SAWarning
from sqlalchemy.orm import Session, configure_mappers

from backend.database import Base
from backend.enums import OpportunityStage, TaskStatus
from backend.models import Activity, Company, Contact, Opportunity, Task, User


class ModelMappingTests(unittest.TestCase):
    def test_relationships_configure_without_overlapping_writes(self):
        with warnings.catch_warnings():
            warnings.simplefilter("error", SAWarning)
            configure_mappers()
        user = User(name="Owner", email="owner@example.test")
        company = Company(name="Customer", owner=user)
        opportunity = Opportunity(name="Deal", company=company, owner=user)
        activity = Activity(
            summary="Discovery call",
            occurred_at=datetime.now(UTC),
            performed_by=user,
            company=company,
            opportunity=opportunity,
        )
        task = Task(
            title="Send proposal",
            due_at=datetime.now(UTC) + timedelta(days=1),
            assignee=user,
            company=company,
            opportunity=opportunity,
        )
        contact = Contact(name="Buyer", company=company)
        self.assertEqual(user.companies, [company])
        self.assertEqual(user.opportunities, [opportunity])
        self.assertEqual(user.activities, [activity])
        self.assertEqual(user.tasks, [task])
        self.assertEqual(company.contacts, [contact])
        self.assertEqual(company.opportunities, [opportunity])
        self.assertEqual(company.activities, [activity])
        self.assertEqual(company.tasks, [task])
        self.assertEqual(opportunity.activities, [activity])
        self.assertEqual(opportunity.tasks, [task])

    def test_postgresql_ddl_includes_native_types_and_constraints(self):
        statements = []
        engine = create_mock_engine(
            "postgresql+psycopg://",
            lambda sql, *args, **kwargs: statements.append(
                str(sql.compile(dialect=engine.dialect))
            ),
        )
        Base.metadata.create_all(engine, checkfirst=False)
        ddl = "\n".join(statements)
        self.assertEqual(len(Base.metadata.tables), 6)
        self.assertEqual(ddl.count("CREATE TABLE"), 6)
        self.assertEqual(ddl.count("CREATE TYPE"), 2)
        for expected in (
            "NUMERIC(18, 2)",
            "TIMESTAMP WITH TIME ZONE",
            "GENERATED BY DEFAULT AS IDENTITY",
            "CHECK (probability BETWEEN 0 AND 100)",
            "CHECK (amount >= 0)",
            "FOREIGN KEY(opportunity_id, company_id)",
            "ON DELETE RESTRICT",
            "'NEW', 'QUALIFIED', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST'",
        ):
            self.assertIn(expected, ddl)


@unittest.skipUnless(os.getenv("TEST_DATABASE_URL"), "TEST_DATABASE_URL is not set")
class PostgreSQLModelTests(unittest.TestCase):
    """Each test creates an isolated schema and rolls back its entire transaction."""

    def setUp(self):
        engine = create_engine(os.environ["TEST_DATABASE_URL"], connect_args={"connect_timeout": 5})
        self.addCleanup(engine.dispose)
        if engine.dialect.name != "postgresql":
            self.fail("Integration tests require PostgreSQL")
        connection = engine.connect()
        self.addCleanup(connection.close)
        transaction = connection.begin()
        self.addCleanup(transaction.rollback)
        schema = "crm_test_" + uuid4().hex
        connection.execute(text(f'CREATE SCHEMA "{schema}"'))
        connection.execute(text(f'SET LOCAL search_path TO "{schema}"'))
        Base.metadata.create_all(connection)
        Base.metadata.create_all(connection)  # Explicit initialization is repeatable.
        self.session = Session(bind=connection, join_transaction_mode="create_savepoint")
        self.addCleanup(self.session.close)
        self.user = User(name="Owner", email="owner@example.test")
        self.company = Company(name="Customer", owner=self.user)
        self.opportunity = Opportunity(
            name="Deal", company=self.company, owner=self.user,
            amount=Decimal("1234567890123456.78"), probability=65,
            expected_close_date=date(2027, 1, 31),
        )
        self.session.add(self.opportunity)
        self.session.flush()

    def test_round_trip_defaults_and_relationships(self):
        occurred_at = datetime.now(UTC) - timedelta(hours=1)
        due_at = datetime.now(UTC) + timedelta(days=1)
        contact = Contact(name="Buyer", company=self.company)
        activity = Activity(
            summary="Call", occurred_at=occurred_at, performed_by=self.user,
            company=self.company, opportunity=self.opportunity,
        )
        task = Task(
            title="Follow up", due_at=due_at, assignee=self.user,
            company=self.company, opportunity=self.opportunity,
        )
        self.session.add_all([contact, activity, task])
        self.session.commit()
        self.session.expire_all()
        self.assertEqual(self.opportunity.amount, Decimal("1234567890123456.78"))
        self.assertIs(self.opportunity.stage, OpportunityStage.NEW)
        self.assertIs(task.status, TaskStatus.TODO)
        self.assertEqual(activity.occurred_at, occurred_at)
        self.assertEqual(task.due_at, due_at)
        self.assertIsNotNone(task.created_at.utcoffset())
        self.assertEqual(self.company.contacts, [contact])
        self.assertEqual(self.company.activities, [activity])
        self.assertEqual(self.company.tasks, [task])
        self.assertEqual(self.opportunity.tasks, [task])
        self.assertEqual(self.opportunity.activities, [activity])
        self.assertEqual(task.assignee, self.user)
        self.assertEqual(activity.performed_by, self.user)
        task.updated_at = datetime(2000, 1, 1, tzinfo=UTC)
        self.session.flush()
        task.status = TaskStatus.DONE
        self.session.flush()
        self.assertGreater(task.updated_at, datetime(2000, 1, 1, tzinfo=UTC))

    def test_optional_links_and_unknown_deal_values(self):
        for company in (None, self.company):
            self.session.add_all([
                Task(title="Reminder", due_at=datetime.now(UTC), assignee=self.user, company=company),
                Activity(summary="Call", occurred_at=datetime.now(UTC), performed_by=self.user, company=company),
            ])
        self.session.add(Opportunity(name="Unknown", company=self.company, owner=self.user))
        self.session.flush()
        unknown = self.session.scalar(select(Opportunity).where(Opportunity.name == "Unknown"))
        self.assertIsNone(unknown.amount)
        self.assertIsNone(unknown.probability)
        self.assertIsNone(unknown.expected_close_date)

    def test_database_rejects_invalid_values(self):
        self.session.add_all([
            Task(title="Reminder", due_at=datetime.now(UTC), assignee=self.user),
            Contact(name="Buyer", company=self.company),
        ])
        self.session.flush()
        cases = (
            ("UPDATE opportunities SET amount = -0.01", "23514"),
            ("UPDATE opportunities SET probability = -1", "23514"),
            ("UPDATE opportunities SET probability = 101", "23514"),
            ("UPDATE opportunities SET stage = 'INVALID'", "22P02"),
            ("UPDATE companies SET owner_id = -1", "23503"),
            ("UPDATE companies SET owner_id = NULL", "23502"),
            ("UPDATE tasks SET status = 'INVALID'", "22P02"),
            ("UPDATE tasks SET due_at = NULL", "23502"),
            ("UPDATE tasks SET assignee_id = NULL", "23502"),
            ("UPDATE contacts SET company_id = NULL", "23502"),
            ("INSERT INTO users (name, email) VALUES ('Duplicate', 'owner@example.test')", "23505"),
        )
        for statement, sqlstate in cases:
            with self.subTest(statement=statement):
                with self.assertRaises(DBAPIError) as raised:
                    with self.session.begin_nested():
                        self.session.execute(text(statement))
                self.assertEqual(raised.exception.orig.sqlstate, sqlstate)

    def test_company_opportunity_consistency_for_both_entities(self):
        other = Company(name="Other", owner=self.user)
        self.session.add(other)
        self.session.flush()
        for model, fields in (
            (Task, {"title": "Reminder", "assignee": self.user, "due_at": datetime.now(UTC)}),
            (Activity, {"summary": "Call", "performed_by": self.user, "occurred_at": datetime.now(UTC)}),
        ):
            for company in (None, other):
                with self.subTest(model=model.__name__, company=company):
                    with self.assertRaises(IntegrityError):
                        with self.session.begin_nested():
                            self.session.add(model(**fields, company=company, opportunity=self.opportunity))
                            self.session.flush()

    def test_deleting_referenced_parents_preserves_business_records(self):
        activity = Activity(
            summary="Call", occurred_at=datetime.now(UTC), performed_by=self.user,
            company=self.company, opportunity=self.opportunity,
        )
        self.session.add(activity)
        self.session.flush()
        for parent in (self.user, self.company, self.opportunity):
            # Exercise deletion with collections already loaded as well.
            for relation in inspect(parent).mapper.relationships:
                if relation.uselist:
                    getattr(parent, relation.key)
            with self.subTest(parent=type(parent).__name__):
                with self.assertRaises(IntegrityError):
                    with self.session.begin_nested():
                        self.session.delete(parent)
                        self.session.flush()
                self.assertIsNotNone(self.session.get(Activity, activity.id))


if __name__ == "__main__":
    unittest.main()
